background_color: "#37474f" # Material blue-grey 800
font: Roboto-Regular
font_color: "#FFFFFF"
signature:
  font_size: 14
  left_text: OZ-DSP v@version
  right_text: ZachOhara.com
  v_offset: 10
  h_offset: 10
defaults:
  knob:
    body_color: "#212121" # Material grey 900
    ring_shade_opacity: 0.7 # between 0 and 1
    rotation_range: 270 # in degrees
    num_sprites: 128
    px80:
      size: 80
      tick:
        width: 5
        height: 25
      ring:
        padding: 7
        thickness: 4
      label:
        font_size: 18
        v_offset: 25
    px120:
      size: 120
      tick:
        width: 10
        height: 30
      ring:
        padding: 7
        thickness: 4
      label:
        font_size: 22
        v_offset: 30
