background_color: "#263238" # Material blue-grey 900
font: Roboto-Regular
font_color: "#FFFFFF"
signature:
  text_1: OZ-DSP v@version
  text_2: ZachOhara.com
  font_size: 14
  width_threshold: 230
  one_line: # When the texts are displayed in the bottom corners
    v_offset: 10
    h_offset: 10
  two_lines: # When the texts are stacked in the bottom center
    v_offset_1: 25
    v_offset_2: 10
object_defaults:
  displaybox:
    body_color: "#0a0a0a"
    corner_radius: 3
  knob:
    body_color: "#0a0a0a"
    ring_shade_opacity: 0.85 # between 0 and 1
    rotation_range: 270 # in degrees
    default_value: 0 # degrees clockwise of center
    num_sprites: 128
    px50:
      size: 50
      tick:
        width: 3
        height: 12
      ring:
        padding: 4
        thickness: 4
      label:
        font_size: 14
        v_offset: 20
      value:
        font_size: 13
        v_offset: -5
    px60:
      size: 60
      tick:
        width: 4
        height: 14
      ring:
        padding: 4
        thickness: 4
      label:
        font_size: 15
        v_offset: 22
      value:
        font_size: 14
        v_offset: -5
    px70:
      size: 70
      tick:
        width: 5
        height: 17
      ring:
        padding: 5
        thickness: 5
      label:
        font_size: 16
        v_offset: 24
      value:
        font_size: 15
        v_offset: -7
    px80:
      size: 80
      tick:
        width: 5
        height: 19
      ring:
        padding: 6
        thickness: 5
      label:
        font_size: 17
        v_offset: 25
      value:
        font_size: 16
        v_offset: -7
    px100:
      size: 100
      tick:
        width: 7
        height: 21
      ring:
        padding: 6
        thickness: 6
      label:
        font_size: 19
        v_offset: 27
      value:
        font_size: 16
        v_offset: -8
    px120:
      size: 120
      tick:
        width: 8
        height: 24
      ring:
        padding: 6
        thickness: 6
      label:
        font_size: 20
        v_offset: 30
      value:
        font_size: 16
        v_offset: -8
  waveform_box:
    body_color: "#0a0a0a"
    graphic_class: displaybox
    line_thickness: 3
    default_value: sine
    px70:
      width: 70
      height: 45
      h_inset: 12
      v_inset: 12
    px80:
      width: 80
      height: 50
      h_inset: 12
      v_inset: 12
