name: NewConfiguration
version: 1.0
width: 400
height: 300
accent_color: "#F44336" # Material red 500
objects:
  example_control:
    class: knob.px80
    label: Example
    value: "50.0%"
    x_pos: 160
    y_pos: 110
parameters:
  example_control:
    hostname: Example
    template: percentage
processors:
  example_processor:
    class: audio.VolumeProcessor
    parameters:
      loudness: example_control
