name: CleanCut
version: 1.1
width: 150
height: 220
accent_color: "#FFFFFF"
objects:
  volume:
    class: knob.px120
    label: Volume
    value: "-0.0 dB"
    x_pos: 75
    y_pos: 100
parameters:
  volume:
    hostname: Volume
    template: volume_reduction
processors:
  volume_processor:
    class: audio.VolumeProcessor
    parameters:
      decibels: volume
