name: Envelope
version: 1.1
width: 320
height: 350
accent_color: "#4CAF50" # Material green 500
objects:
  attack:
    class: knob.px60
    label: Attack
    value: "100 ms"
    x_pos: 16
    y_pos: 30
  decay:
    class: knob.px60
    label: Decay
    value: "100 ms"
    x_pos: 92
    y_pos: 30
  sustain:
    class: knob.px60
    label: Sustain
    value: "50.0%"
    x_pos: 168
    y_pos: 30
  release:
    class: knob.px60
    label: Release
    value: "100 ms"
    x_pos: 244
    y_pos: 30
  attack_shape:
    class: knob.px50
    label: A. Shape
    value: "0.0"
    x_pos: 60
    y_pos: 130
  decay_shape:
    class: knob.px50
    label: D. Shape
    value: "0.0"
    x_pos: 135
    y_pos: 130
  release_shape:
    class: knob.px50
    label: R. Shape
    value: "0.0"
    x_pos: 210
    y_pos: 130
  envelope_display:
    class: displaybox
    width: 290
    height: 120
    x_pos: 15
    y_pos: 200
