name: Envelope
version: 1.1
width: 320
height: 350
accent_color: "#4CAF50" # Material green 500
objects:
  attack_time:
    class: knob.px60
    label: Attack
    value: "100 ms"
    x_pos: 46
    y_pos: 60
  decay_time:
    class: knob.px60
    label: Decay
    value: "100 ms"
    x_pos: 122
    y_pos: 60
  sustain_level:
    class: knob.px60
    label: Sustain
    value: "50.0%"
    x_pos: 198
    y_pos: 60
  release_time:
    class: knob.px60
    label: Release
    value: "100 ms"
    x_pos: 274
    y_pos: 60
  attack_shape:
    class: knob.px50
    label: A. Shape
    value: "0.0"
    x_pos: 61
    y_pos: 155
  decay_shape:
    class: knob.px50
    label: D. Shape
    value: "0.0"
    x_pos: 127
    y_pos: 155
  peak_level:
    class: knob.px50
    label: Peak
    value: "50.0%"
    x_pos: 193
    y_pos: 155
  release_shape:
    class: knob.px50
    label: R. Shape
    value: "0.0"
    x_pos: 259
    y_pos: 155
  envelope_display:
    class: displaybox
    width: 290
    height: 120
    x_pos: 160
    y_pos: 260
parameters:
  attack_time:
    hostname: Attack
    template: envelope_time
  decay_time:
    hostname: Decay
    template: envelope_time
  sustain_level:
    hostname: Sustain
    template: percentage
  release_time:
    hostname: Release
    template: envelope_time
  attack_shape:
    hostname: Attack Shape
    template: envelope_shape
  decay_shape:
    hostname: Decay Shape
    template: envelope_shape
  peak_level:
    hostname: Peak
    template: percentage
  release_shape:
    hostname: Release Shape
    template: envelope_shape
processors:
  oscillator:
    class: audio.Oscillator
  tuning_processor:
    class: midi.TuningProcessor
  envelope_processor:
    class: audio.EnvelopeProcessor
    parameters:
      attack_time: attack_time
      decay_time: decay_time
      sustain_level: sustain_level
      release_time: release_time
      peak_level: peak_level
      attack_shape: attack_shape
      decay_shape: decay_shape
      release_shape: release_shape
