name: Overdrive
version: 1.1
width: 340
height: 160
accent_color: "#F44336" # Material red 500
objects:
  drive:
    class: knob.px80
    label: Drive
    value: "50.0%"
    x_pos: 70
    y_pos: 70
  tone:
    class: knob.px80
    label: Tone
    value: "50.0%"
    x_pos: 170
    y_pos: 70
  volume:
    class: knob.px80
    label: Volume
    value: "-0.0 dB"
    x_pos: 270
    y_pos: 70
parameters:
  drive:
    hostname: Drive
    template: percentage
  tone:
    hostname: Tone
    template: percentage
  volume:
    hostname: Volume
    template: volume_reduction
processors:
  tone_processor:
    class: audio.ToneMixProcessor
    parameters:
      mix_percent: tone
  volume_processor:
    class: audio.VolumeProcessor
    parameters:
      decibels: volume
