name: Overdrive
version: 1.1
width: 340
height: 160
accent_color: "#F44336" # Material red 500
objects:
  drive:
    class: knob.px80
    label: Drive
    value: "50.0%"
    x_pos: 30
    y_pos: 30
  tone:
    class: knob.px80
    label: Tone
    value: "50.0%"
    x_pos: 130
    y_pos: 30
  volume:
    class: knob.px80
    label: Volume
    value: "-0.0 dB"
    x_pos: 230
    y_pos: 30
