name: SamplePlugin
version: 1.0
width: 500
height: 300
accent_color: "#F44336" # Material red 500
controls:
  volume:
    label: Volume
    type: knob
    variant: px80
    x_pos: 300
    y_pos: 150
  pitch:
    label: Pitch
    value: "440 hz"
    type: knob
    variant: px120
    x_pos: 50
    y_pos: 100

