name: ToneGen
version: 1.1
width: 250
height: 210
accent_color: "#009688" # Material teal 500
objects:
  pitch:
    class: knob.px100
    label: Pitch
    value: "440 hz"
    x_pos: 76
    y_pos: 100
  volume:
    class: knob.px80
    label: Volume
    value: "-0.0 dB"
    x_pos: 190
    y_pos: 125
  waveform:
    class: waveform_box.px70
    x_pos: 190
    y_pos: 32
parameters:
  pitch:
    hostname: Pitch
    template: frequency
  volume:
    hostname: Volume
    template: volume_reduction
  waveform:
    hostname: Waveform
    template: waveform
processors:
  oscillator:
    class: audio.Oscillator
    parameters:
      Frequency: pitch
      Waveform: waveform
  volume_processor:
    class: audio.VolumeProcessor
    parameters:
      decibels: volume
