name: ToneGen
version: 1.1
width: 250
height: 210
accent_color: "#009688" # Material teal 500
objects:
  pitch:
    class: knob.px100
    label: Pitch
    value: "440 hz"
    x_pos: 26
    y_pos: 50
  volume:
    class: knob.px80
    label: Volume
    value: "-0.0 dB"
    x_pos: 150
    y_pos: 85
  waveform:
    class: waveform_box.px70
    x_pos: 155
    y_pos: 10
parameters:
  pitch:
    hostname: Pitch
    template: frequency
  volume:
    hostname: Volume
    template: volume_reduction
  waveform:
    hostname: Waveform
    template: waveform
processors:
  oscillator:
    class: audio.Oscillator
    parameters:
      Frequency: pitch
      Waveform: waveform
  volumeProcessor:
    class: audio.VolumeProcessor
    parameters:
      Decibels: volume
