name: ToneGen
version: 1.1
width: 250
height: 210
accent_color: "#009688" # Material teal 500
controls:
  pitch:
    label: Pitch
    value: "440 hz"
    type: knob
    variant: px100
    x_pos: 26
    y_pos: 50
  volume:
    label: Volume
    value: "-0.0 dB"
    type: knob
    variant: px80
    x_pos: 150
    y_pos: 85
  waveform:
    type: waveform_box
    value: sine
    variant: px70
    x_pos: 155
    y_pos: 10
